### ISSUE TITLE
Unfortunately the referenced packet documentation missed some information

### ISSUE THREAD

**Issue by dirk68-fu** [petersimonsson/libqatemcontrol#26]
Unfortunately the [referenced](http://atemuser.com/forums/atem-vision-mixers/developers/controlling-atem#comment-251) packet documentation misses some information:

> The packets are structured as following - [] represents 1 byte:
> [CCCCCLLL][LLLLLLLL][UH][UL][JH][JL][?][?][?][?][KH][KL] ... [VH][VL][P1]-[Pn]
> 
> C are command bits:
> bit 8 means: send ACK for (packet with bit 4 and Counter 'K' set)
> - fill counter 'J' with value of counter 'K'
> bit 7 means: no idea at all
> bit 6 means: this is an resend packet
> bit 5 means: this is an hello packet
> bit 4 means: request acknowledge for this packet, fill counter 'K' with incremental packet number
> 
> L is the lenght, as you can see, it's 11 bits, the 3 higher bits are stored in the command byte.
> 
> U is the uid, when connecting to the atem, you choose a random one (afaik).
> After successfull hello, the mixer answers with his configuration and your "new" uid.
> Do not ack the configuration packets until their payload is 0 (means L is 12 decimal).
> 
> J and K are counters. The atem and the control panel use, let's call it communication channels,
> using the command bits 8 and 4 and incrementing these counter's resp. acking the packet of the opposite site.
> 
> The part's with [?] i don't know anything about :)
> 
> The payload is, as described above just 2 byte length and then the payload (the 2 bytes len are included in the length calculation). So if you get a packet, check for L, and if it's greater than 12 dec, read ahead the next 2 bytes, read the payload and so on.

In the cited description remain at least two questions:

1) What is the function of [VH][VL]?
2) What ist meant by "..." between K und V?

and additinally the explanation of J and K is unfortunately not easily understandable.

**Yes I know, you didn't write this, but it would be really great if someone who already understood this, could _please_ elaborate more. Thanks!**

**Comment by Julusian** [comment]
[VH][VL] define the payload length. I would guess that the ... before it indicates that the payload length bytes may not exist (if the packet is a ping), but there are no more bytes between [KL] and [VH]

J is the ack id. So is set only when the current packet is an ack and it gets set to the id of the packet the ack is in response to
K is the packet id. An incrementing 7bit int. Should be increased for each packet that sets the 'request acknowledge' bit. you should send an ack for each packet you receive with this, otherwise the atem will retransmit the packet to you after a few hundred milliseconds.

The rest of that looks to match what I have got in my code.
Hope this helps :)
